export const ADD_WORD = 'ADD_WORD';
export const DELETE_WORD = 'DELETE_WORD';
export const EDIT_WORD = 'EDIT_WORD';
export const SAVE_LEARNED_WORDS = 'SAVE_LEARNED_WORDS';
export const SET_CURRENT_LANGUAGE = 'SET_CURRENT_LANGUAGE';
export const ADD_LANGUAGE = 'ADD_LANGUAGE';
export const DELETE_LANGUAGE = 'DELETE_LANGUAGE';
