const Wording = {
  selectWord: 'Select word from suggestions',
  or: 'or',
  addWord: 'Add own description',
  addToLearning: 'Add to learning',
  original: 'en: ',
  translated: 'en: ',
  createFromCamera: 'Create from Camera',
  selectPicture: 'Select Picture',
  study: 'Study',
  next: 'Next',
  studied: 'Studied: ',
  correctStudied: 'Correct: ',
  finish: 'Finish',
  delete: 'Delete',
  deleteTitle: 'Delete word?',
  deleteText: 'Are you sure you want to delete word?',
  edit: 'Edit',
  source: 'Source',
  translation: 'Translation',
  save: 'Save',
  dictionary: 'Dictionary',
  creation: 'Creation',
  editWord: 'Edit word',
  menu: 'Menu',
  notEnoughWords: 'Not enough words for learning',
  sorry: 'Sorry',
};

export default Wording;
